project:
  name: "methane-detection-starcop"
  experiment_name: "segformer-b0-v1"

storage:
  drive_data_easy_train: "https://drive.google.com/uc?id=1C4ZHvT1ZPKVMFGmqcV12Aozs8Uv_DIxD"
  drive_data_test : "https://drive.google.com/uc?id=1TwtSVpbvGd-lWfIjQrw0i4LqkiX2EuHq"
  local_raw_path: "data"
  local_results_path: "results"


training:
  num_xp: 3
  n_folds: 5
  batch_size: 8
  n_total_epochs: 15
  n_epochs_before_unfreeze: 5
  warmup_epochs: 2
  freeze_lr: 1e-3
  unfreeze_lr: 5e-3
  weight_decay: 1e-5
  img_size: 512
  num_workers: 4
  device: "cuda"
  loss: "dice"  #or "cross_entropy" or "focal" or "combined"
  model: "MiT"  #or "MiT"
  method: "concat"
  n_swir: 8 #max 8
  load_zip_data: True
  